### ISSUE TITLE
Ruby 2.7.4, 3..0.2

### ISSUE THREAD

**Issue by marcelotoledo5000** [taq/traquitana#5]
Hi,

Isn't working with Ruby 2.7.4 and 3.0.2

```
Configs not found (tried '' and 'config/traq.yml')
Running Traquitana version 0.1.7

Configs not found (tried '' and 'config/traq.yml')
Traceback (most recent call last):
	4: from /home/marcelo/.asdf/installs/ruby/2.7.4/bin/traq:23:in `<main>'
	3: from /home/marcelo/.asdf/installs/ruby/2.7.4/bin/traq:23:in `load'
	2: from /home/marcelo/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/traquitana-0.1.7/bin/traq:44:in `<top (required)>'
	1: from /home/marcelo/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/traquitana-0.1.7/lib/deployer.rb:22:in `run'
/home/marcelo/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/traquitana-0.1.7/lib/config.rb:26:in `method_missing': undefined method `[]' for nil:NilClass (NoMethodError)
```

PS: The same setup to Ruby 2.7.2 is working

**Comment by taq** [comment]
Just deployed with 2.7.4 and 3.0.2 and worked ok. 

If you take a look on your errors messages, it's weird, it's not finding the config files, then on line 26 on config.rb it nullify the config hash. On my deploys here with the default config file everything is ok. Are you using the targets?

**Comment by marcelotoledo5000** [comment]
I don't know why, but, I tried and receive this error message. Yes, I'm using two targets that working normal when I use only ruby 2.7.2 version.

**Comment by taq** [comment]
I couldn't reproduce what is wrong, so you'll need to take a look on the code and submit a patch. Meanwhile, I'll close this issue.

**Comment by marcelotoledo5000** [comment]
Don't worry, was fixed using the 2.7.5 version... ;)
